### ISSUE TITLE
mp4 and metadata do not end up in the same folder given the same file path

### ISSUE THREAD

**Issue by ionapjolive** [drawrowfly/tiktok-scraper#134]
**Describe the bug**
mp4 and metadata do not end up in the same folder given the same file path.

**To Reproduce**
- Run a command such as tiktok-scraper user <tiktokusername> -d -n 1 -s -t json --filepath /home/iona
- The mp4 is saved in the folder /home/iona/tiktokusername, but the json is saved in /home/iona

- Used Ubuntu 18.04.4, Digital Ocean Droplet
- NodeJs Version v14.2.0
- Scraper Version 1.1.10
- CLI
- Used method tiktok-scraper user <tiktokusername> -d -n 1 -s -t json --filepath /home/iona
- Used options download, number, filepath, filetype, save
- Do you run the scraper through Proxy, VPN, VPS? No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! Yes, it is public and all files downloaded, just not in expected folders

**Comment by drawrowfly** [comment]
That is the correct behavior, user videos will be saved in newly created or already existing  filepath/folder for that username and metadata files will be saved in filepath . 

If you will set zip value to true then videos will be zipped and saved with the metadata files in the same filepath . 

Anyway i can change it so that the metadata files will be saved to the folder with the videos if zip is false

**Comment by paulwongx** [comment]
> That is the correct behavior, user videos will be saved in newly created or already existing filepath/folder for that username and metadata files will be saved in filepath .
> 
> If you will set zip value to true then videos will be zipped and saved with the metadata files in the same filepath .
> 
> Anyway i can change it so that the metadata files will be saved to the folder with the videos if zip is false

Is there an option to save it all in the same folder as per historical practice? Thanks.

**Comment by drawrowfly** [comment]
Fix in the latest update
