### ISSUE TITLE
How to handle hitting rate limit with large accounts?

### ISSUE THREAD

**Issue by TheFirsh** [drawrowfly/tiktok-scraper#241]
So I wanted to download a user with 400+ videos and after about 200, the tool began saving 0 byte videos. I also ran into some occurrences of an error page and/or 403 HTML being written into the mp4 file. Yet the history seems to store them as "done". There could be a check for under x KB in size and if so, it should not be logged in history. That would allow a later retry. If I plan on constantly downloading thousands of vids without a proxy what timeout should I use to be able to constantly download, what is the rate limit?

**Comment by Liz-chan** [comment]
Usually when that happens to me I delete all the 0 byte videos from the history file and the files themselves and then wait an hour and try again. A good way to improve this tool would be to detect when 0 byte videos start being saved and to not save them in the history file or the file itself and stop right away. There could also be an option to wait for a period of time and then start again without having to run the tool again manually.

**Comment by TheFirsh** [comment]
I think rather than editing the history file manually, I'd just write a little script to rebuild it based on what's found in the folder (after I deleted the 0-byte files). Or there could be an option in the tool to skip existing files (no overwrite).

**Comment by drawrowfly** [comment]
I will check what i can do for such cases, but always use proxies if you use this tool intensively

**Comment by Liz-chan** [comment]
I think it would also be good if the program didn't add a video ID to the history file if "download=false".

**Comment by TheFirsh** [comment]
Do you have any recommendations for such proxies? For me that = pair VPN or an AWS EC2 instance with VPN server on it, but it's too much work.

For now, here is my workaround without proxy:

job-pszincs.bat
`tiktok-scraper user pszincs --hd --noWaterMark --store --download --asyncDownload 1 --timeout 20000 --filetype json --historypath "P:\TikTok"`

Timeout doesn't make it wait 20s tho. If this were a large account, I'd delete the 0-byte files by hand then run this:

rebuild-history-for-pszincs-6735889893144314885.py

```
import os

history_file = "6735889893144314885.json"
directory = os.fsencode("pszincs")
ids = []

for file in os.listdir(directory):
     filename = os.fsdecode(file)
     if filename.endswith(".mp4"): 
         ids.append(os.path.splitext(filename)[0])
         continue
     else:
         continue

history_content = '["' + '","'.join(ids) + '"]'

f = open(history_file, "w+") 
f.write(history_content)
f.close()
```

I just write the ID from the history filename into the filename of the rebuild so I know which history is which. You can get/verify the user ID with this too: `tiktok-scraper userprofile z0odles`.

So I rebuild the history then run the download again and again (after the ratelimit is gone) until it is complete and no more 0-bytes. Would be possible to autodelete all 0-bytes with the .py script but for now, I do it by hand.

I have a Windows-scheduled all-tiktok-jobs.bat with this in it:
```
cd /D "%~dp0"
for  %%x in (job-*.bat) do (
	@echo Calling %%x...
	@echo | call %%x
)
```
That'll keep them up to date if ran once a day. Large accounts take forever (I guess paging in the background, before video downloads start), even if there is nothing new.

**Comment by drawrowfly** [comment]
just buy few ipv4 proxies and use other cloud provider as it will be cheaper then ec2

**Comment by reallyuniquename** [comment]
@drawrowfly
Would it be possible to handle this kind of issues and automatically retry video download or pause the script on error? I'd love to see at least an indication of error because right now script fails silently. 

I didn't even realize that until I noticed that number of downloaded videos was less than the one written in history file. By the way it's probably a good idea to write history file only when video is actually downloaded.

**Comment by RazeBerry** [comment]
@drawrowfly An additional issue I have faced is that even using VPN with brand new IP addresses, the scraper sometimes return nothing or simply time out. Sometimes it only scrape three videos and it stops. Not sure why is that happening. But it seems like you can fix the issue by simply reinstalling the python package.

**Comment by LamaRaz** [comment]
it wouldn't happen if a state machine paradigm was used
unless the download is completed why would you insert the id into the history?

also I'm assuming the in-progress download happens in /tmp/ somewhere or in memory since I don't see any incomplete/temp files in directory, which is good. this means all videos in the directory should be complete and their ids can be used to exclude downloads instead of a useless history file... why isn't this happening?

**Comment by reallyuniquename** [comment]
Let's not bash the developer here, @drawrowfly did insane job.

>all videos in the directory should be complete and their ids can be used to exclude downloads instead of a useless history file... 
>why isn't this happening?

Because not everyone keeps downloaded videos on the same machine you run scraper on.

**Comment by LamaRaz** [comment]
> Let's not bash the developer here, @drawrowfly did insane job.
> 
> > all videos in the directory should be complete and their ids can be used to exclude downloads instead of a useless history file...
> > why isn't this happening?
> 
> Because not everyone keeps downloaded videos on the same machine you run scraper on.

Didn't mean to bash, sorry if it came out that way.

If you are keeping the videos on another machine then why not ls the directory and get the ids that way? You are presumably connected to both or on one of the machines.

**Comment by reallyuniquename** [comment]
That's what json history files do, they keep track of what's been downloaded so you don't need to have actual videos or keep their original name. You can even delete some and scraper would not pick them up again. That's very neat.

But I get your reasoning, having an _option_ to rely on a list of files is OK.

**Comment by LamaRaz** [comment]
It wouldn't be a problem if the software saved proper state. Also some of the downloaded files do appear to be corrupt (probably incomplete, but can't even start in a player).

It is not good practice to save files that have no guarantee of not being corrupt/incomplete and the software unable to even determine that on the next round. All in-progress downloads should be temp and after their are completed should they be marked as such after being validated with the HTTP headers and perhaps even ffmpeg.


Unfortunately I'm not willing to learn javascript just for this project, and no one seems to have anything better on github.

**Comment by drawrowfly** [comment]
Patience! There was a reasons why I did it , don't remember what exactly but there was !

I will update this repo shortly with better way of handling things

**Comment by dannyvoid** [comment]
> Would be possible to autodelete all 0-bytes with the .py script but for now, I do it by hand.

I've pretty much also have adapted your solution. Just added this to the beginning of the scrape-all bat.

`powershell -Command "Get-ChildItem -Path 'P:\TikTok' -Recurse -Force | Where-Object { $_.PSIsContainer -eq $false -and $_.Length -eq 0 }  | remove-item"`

**Comment by ItsABlackScreen** [comment]
I wrote a script for error checking the output from the program. It can delete 'Zero' files and check if all the files have downloaded correctly. Link for any interested:
  <a href= "https://github.com/ItsABlackScreen/ErrorChecking-tiktok-scraper">ErrorChecking-tiktok-scraper</a>

**Comment by Gorrrg** [comment]
I've stumbled across a related network issue that's causing bogus video files to be created by the same underlying error handling issue. Some videos would not download because of --hd and possibly --noWaterMark options as well my geolocation. I was able to get more HD videos without a watermark by using a VPN and "going" to another country. And of course omitting the HD and noWaterMark options lets you get all the videos that are not geoblocked.

But anyway the topic here is zero length MP4s (and MP4s with error responses in them as well I suppose) so anyway, I've also come up with a script to rebuild the downloads JSON before I saw this thread and then I added dannyvoid's command to delete the bogus files. Use at your own risk, it's for PowerShell and it needs to be executed from the directory where the MP4 files are located. (I'll probably change it to work from the parent directory and process all TikTok users in one go.)

```$Downloads = @()
$Path = Get-Location
$UserID = (Get-Item $Path).Name

foreach ( $File in ( Get-ChildItem -Path $Path *.mp4 ) ) {
    if ( $File.Length -lt 50000 ) {
        Remove-Item $File
    } else {
        $Downloads += $File.BaseName
    }
}

$Downloads = $Downloads | Sort-Object -Descending | ConvertTo-Json
Out-File -InputObject $Downloads -Encoding utf8NoBOM -FilePath "..\$UserID.json"
```

You will have to change the JSON's file name to the numeral user ID manually and then copy it to your history directory.

**Comment by drawrowfly** [comment]
TikTok api is very unpredictable this days. As of right now the best solution is to use proxies

**Comment by reallyuniquename** [comment]
@drawrowfly Is it me or history file gets saved only after every queued video has been downloaded? 

For example I downloaded 40 out of 100 files, something went wrong and script was terminated but `history.json` and `1234567890.json` have not been updated.
