### ISSUE TITLE
Support for Hebrew alphabet?

### ISSUE THREAD

**Issue by iliterat** [drawrowfly/tiktok-scraper#28]
The scraper doesn't seem to work when the keyword (e.g. the hashtag I search for) is in Hebrew script. The word does show up in Hebrew alphabet in Terminal and I have Unicode (UTF-8) text encoding enabled, so I don't think the issue is with Terminal. Can you advise? Thanks!

**Comment by drawrowfly** [comment]
Will take a look at it later

As always PR is welcome

**Comment by charlesLoder** [comment]
Hey, so I decided to take a look at this, but I didn't want to submit a PR without a little discussion first because I'm more of a hobbyist programmer and still relatively new to open source.

Adding a simple `encodeURIComponent()` seems to work:
```javascript
// ./lib/index.js

/**
  * Get hashtag ID
  */
    async getHashTagId() {
        try {
            return await this.getIds({
                uri: `${this.mainHost}node/share/tag/${encodeURIComponent(this.input)}`,
                type: 'hashtag',
            });
        } catch (error) {
            throw new Error(error);
        }
    }
```
And also at lines `240` and `643`.

Just testing it out worked fine:
```javascript
// test.js

const TikTokScraper = require('./index.js');

const ibriyt = 'עברית';

(async () => {
    try {
        const posts = await TikTokScraper.hashtag(ibriyt, {number: 1});
        console.log(posts);
    } catch (error) {
        console.log(error);
    }
})();
```
Without a test suite, I wasn't sure if this would introduce more bugs though.

**Comment by drawrowfly** [comment]
Works now from the latest version

@charlesLoder i still appreciate your efforts with the pull requests, from now all the tests are done after you submit the pull! Thank You
