### ISSUE TITLE
Download no watermark video

### ISSUE THREAD

**Issue by lau1944** [drawrowfly/tiktok-scraper#513]
I understand this library does not support no watermark video for now, does it have plan to support it in the future?

**Comment by drawrowfly** [comment]
Probably yes

**Comment by Genusatplay** [comment]
Some sites `https://tiktokfull.com/?lang=en` can download without a watermark. Any ideas on how to download now without a watermark?

**Comment by kevin4dhd** [comment]
Any solution?

**Comment by UnixCro** [comment]
It is currently not possible to download Tiktok videos without watermarks using the browser programming interface.  Other websites use the mobile programming interface.  If you use the whole normal Tiktok app then you will find that there is no watermark there.  This is what is meant by Mobile API (programming interface).  In order to use this, however, I think you have to reverse engineer it because the source code is closed.  My idea was to run it via a third party website and download it from there, but then this repository is no longer really open source and who knows what the website owner is doing with the data from you.  So I can partially understand the owner of this project.  I would like to see if the download from the website is not installed in tiktok-scraper but in a different one, I now say inferior repository and not with tiktok-scraper that thousands of people classify as safe.

**Comment by nvmnghia** [comment]
@UnixCro So it is entirely possible?
